### ISSUE TITLE
Mechanics and boon table addons not showing up

### ISSUE THREAD

**Issue by davidlukerice** [fmmmlee/GW2-Addon-Manager#12]
### Please attach a copy of config.yaml or config.ini to the issue.
```
application_version: v1.0.0
loader_version: v0.1
bin_folder: bin64
isupdate: true
game_path: C:\Program Files\Guild Wars 2
default_configuration:
  d3d9_wrapper: false
  arcdps: true
  arcdps_boontable: true
  arcdps_mechanics: true
  d912pxy: true
version:
  d3d9_wrapper: v1.0
  arcdps: >
    21f2d1279e0b904e93ce788559ec83da  x64/d3d9.dll
  arcdps_boontable: v1.0
  arcdps_mechanics: v1.0
  d912pxy: v1.9h2
installed:
  d3d9_wrapper: d3d9_wrapper
  arcdps: arcdps
  arcdps_boontable: arcdps_boontable
  arcdps_mechanics: arcdps_mechanics
  d912pxy: d912pxy
disabled:
  d3d9_wrapper: false
  arcdps: false
  arcdps_boontable: false
  arcdps_mechanics: false
  d912pxy: false
```

**Describe the bug**
I updated to v1.0 following the instructions of clearing the bin64 folder, starting GW2, then installing the addon manager. I've added arcdps, boon table, mechanics, and d912pxy via the ui and started the game. Both arcdps and d912 proxy work fine but the boon table and mechanics log don't show up. Both dlls look to have been downloaded into the addons/arcdps folder, but don't seem to be running.

**To Reproduce**
- Following instructions for updating to v1.0 (aka. delete bin64 folder, start gw2, then install addon manager and plugins)
- Start up the game
- Notice boon table and mechanics log plugins aren't running

**Additional context**
Was running v0.4.5 before this without issue.
